enum EventTypes {
  UPDATE_OPTIONS = 'UPDATE_OPTIONS',
  SET_FRACTION = 'SET_FRACTION',
  SET_STEP_VALUE = 'SET_STEP_VALUE',
  VALIDATE = 'VALIDATE',
  VALUE_CHANGE = 'VALUE_CHANGE',
  UPDATE = 'UPDATE',
}

export default EventTypes;
