enum EventTypes {
  UPDATE_OPTIONS = 'UPDATE_OPTIONS',
  SET_FRACTION = 'SET_FRACTION',
  SET_STEP_VALUE = 'SET_STEP_VALUE',
  VALIDATE_VALUE = 'VALIDATE_VALUE',
  VALUE_CHANGE = 'VALUE_CHANGE',
  UPDATE_VALUE = 'UPDATE_VALUE',
}

export default EventTypes;
