enum EventTypes {
  UPDATE_OPTIONS = 'UPDATE_OPTIONS',
  SET_FRACTION = 'SET_FRACTION',
  SET_STEP_VALID_VALUE = 'SET_STEP_VALID_VALUE',
  VALIDATE_VALUE = 'VALIDATE_VALUE',
  VALUE_CHANGE = 'VALUE_CHANGE',
  UPDATE_VALUE = 'UPDATE_VALUE',
  SET_STEP_VALUES = 'SET_STEP_VALUES',
}

export default EventTypes;
